version: '3'

vars:
  APP_NAME: myapp

tasks:
  migrate_up:
    desc: Migrations UP completed success
    cmds:
      - migrate -path ./services/migrations -database "postgres://postgres:test@localhost:5432/med_note?sslmode=disable" up

  migrate_down:
    desc: Migrations DOWN completed success
    cmds:
      - migrate -path ./services/migrations -database "postgres://postgres:test@localhost:5432/med_note?sslmode=disable" down

  load_env:
    desc: Load environment variables from .env file in local terminal session
    cmds:
      - bash -c 'source load_env.sh'